version: 1
accounts:
- name: alice
  coins:
  - 200000000000000ugd
  cointype: 88888888
- name: bob
  coins:
  - 200000000000000ugd
  cointype: 88888888
- name: janus
  coins:
  - 200000000000000ugd
  mnemonic: vacuum toss steel skull skirt hip acoustic desert photo hotel boss leg fire shaft novel panther shield track hub cover bleak admit merry skate
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 100000ugd
validators:
- name: alice
  bonded: 100000000ugd
genesis:
  app_state:
    staking:
      params:
        bond_denom: "ugd"
